# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.omnibus.chef_version = "11.4.0"
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.define :web01 do |web|
    web.vm.network :private_network, ip: "192.168.30.10"

    #web.vm.provision :chef_solo do |chef|
    #  chef.cookbooks_path = "./cookbooks"
    #  chef.add_recipe "apache"
    #  chef.json = {
    #  }
    #end
  end
end
