# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

HOST_NUM = 2
IP_BASE = "192.168.33"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "yungsang/coreos-beta"

  (1..HOST_NUM).each do |i|
    master = i == 1 ? true : false
    hostname = "host#{i}"
    ip = "#{IP_BASE}.#{i+10}"

    config.vm.define vm_name = hostname do |host|
      host.vm.hostname = hostname
      host.vm.network :private_network, ip: ip

      # coreos cloudinit
      if master
        host.vm.provision :file, preserve_order: true, source: "cloud_config/master.yml", destination: "./cloud_config.yml"
      else
        host.vm.provision :file, preserve_order: true, source: "cloud_config/node.yml", destination: "./cloud_config.yml"
      end
      host.vm.provision :shell, preserve_order: true do |sh|
        sh.inline = <<-EOT
          sed -e \'s/%master-ip%/#{IP_BASE}.11/g\' -i ./cloud_config.yml
          sed -e \'s/%ip%/#{ip}/g\' -i ./cloud_config.yml
          coreos-cloudinit -from-file=./cloud_config.yml
        EOT
      end

      # docker pull
      host.vm.provision :docker, preserve_order: true do |d|
        d.pull_images "ubuntu:trusty"
      end
    end
  end
end
