name             'dev'
maintainer       'foostan'
maintainer_email 'dev@fstn.jp'
license          'MIT'
description      'Installs/Configures dev'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
recommends       'git'
recommends       'zsh'
recommends       'screen'
recommends       'vim'
